POST http://localhost:8080/addexpense
Content-Type: application/json

{
    "title": "Dinner with friends",
    "amount": 100.00,
    "group_id": 1,
    "payor_id": 2,
    "custom_split": [
        {"user_id": 1, "owed_amount": 80.00},
        {"user_id": 3, "owed_amount": 10.00}
    ]
}
