POST http://localhost:8080/addgroup
Content-Type: application/json

{
    "name": "Home",
    "creator_id": 1,
    "members": [
        {"user_id": 1},
        {"user_id": 2},
        {"user_id": 3},
        {"user_id": 4}
    ]
}
